theme: jekyll-theme-minimal

avatar: 'img/Ricardo.jpg'

github_username:   RicJM
orcid_id:          0000-0001-8261-4409
google_scholar_id: hkriDdcAAAAJ
#researchgate_user: Ricardo_Marques
#linkedin_user:     ricardo-marques